### ISSUE TITLE
[SPIKE] Convert Thoth website to a Gatsby site

### ISSUE THREAD

**Issue by Gkrumbach07** [thoth-station/thoth-station.github.io#245]
**Is your feature request related to a problem? Please describe.**
As a Thoth user, I want all Thoth related sites to have the same UI and share navigation to make the Thoth sites feel more uniform.

**Describe the solution you'd like**
Convert the Thoth site and its content to a [Gatsby JS](https://www.gatsbyjs.com/) site and have better navigation for the documentation.

**Additional context**

Gastby can be used to pull markdown files (or any other files), format them, and render them in a consistent way using React. Operate First's old website did this and their new site also uses Gatsby but doesn't pull markdown data.

- Operate First new website: https://github.com/operate-first/operate-first.github.io
- Operate First old website: https://github.com/operate-first/operate-first.github.io-old
- Thoth Help site: https://thoth-station.ninja/help/
- Thoth Website: https://thoth-station.ninja
- current Doc generation: https://github.com/thoth-station/nepthys

**Acceptance Criteria**

- [ ] Gatsby site looks like Thoths [current website](https://thoth-station.ninja) in terms of formatting, color, structure.
- [ ] Gastby site renders documentation using Gastby nodes (see Thoth help page and old operate first site for implementation)

**Comment by codificat** [comment]
/reopen
after the discussion in today's tech talk

**Comment by Gkrumbach07** [comment]
Decided web technologies used:
- Gatsby (React framework)
- MUI Joy (theme and component library)
- Storybooks and Chromatic (UI Testing, UI docs, UI CI/CD)
